---
services:
  app:
    build:
      context: .
      args:
        PHP_TAG: '8.4-cli-bookworm'
        COMPOSER_TAG: '2.8'
    environment:
      PHP_IDE_CONFIG: 'serverName=ekwi-tech/composer-attribute-collector'
    volumes:
      - .:/app:delegated
      - ~/.composer:/root/.composer:delegated
    working_dir: /app
