<?php

namespace olvlvl\ComposerAttributeCollector;

use function array_map;
use function implode;
use function is_array;
use function var_export;

/**
 * Renders collected attribute targets as PHP code.
 *
 * Only the names of the attributes and their targets are rendered. Attribute arguments are
 * deliberately left out: they can hold arbitrary values—objects, in particular—that cannot be
 * exported as PHP code.
 *
 * @internal
 */
final class TransientCollectionRenderer
{
    private const INDENT = '    ';

    public static function render(TransientCollection $collector): string
    {
        $targetClassesCode = self::targetsToCode($collector->classes);
        $targetMethodsCode = self::targetsToCode($collector->methods);
        $targetPropertiesCode = self::targetsToCode($collector->properties);
        $targetParametersCode = self::targetsToCode($collector->parameters);

        return <<<PHP
        <?php

        // attributes.php @generated by https://github.com/olvlvl/composer-attribute-collector

        \olvlvl\ComposerAttributeCollector\Attributes::with(fn () => new \olvlvl\ComposerAttributeCollector\Collection(
            targetClasses: $targetClassesCode,
            targetMethods: $targetMethodsCode,
            targetProperties: $targetPropertiesCode,
            targetParameters: $targetParametersCode,
        ));
        PHP;
    }

    /**
     * //phpcs:disable Generic.Files.LineLength.TooLong
     *
     * @param iterable<class-string, iterable<TransientTargetClass|TransientTargetMethod|TransientTargetParameter|TransientTargetProperty>> $targetByClass
     *
     * @return string
     */
    private static function targetsToCode(iterable $targetByClass): string
    {
        $array = self::targetsToArray($targetByClass);

        if (!$array) {
            return '[]';
        }

        $indent = self::INDENT;
        $code = "[\n";

        foreach ($array as $attribute => $targets) {
            $code .= "$indent$indent" . self::exportString($attribute) . " => [\n";

            foreach ($targets as $target) {
                $code .= "$indent$indent$indent" . self::exportTarget($target) . ",\n";
            }

            $code .= "$indent$indent],\n";
        }

        return $code . "$indent]";
    }

    /**
     * @param string|array<string> $target
     */
    private static function exportTarget(string|array $target): string
    {
        if (is_array($target)) {
            $exported = array_map(fn(string $v): string => self::exportString($v), $target);

            return '[ ' . implode(', ', $exported) . ' ]';
        }

        return self::exportString($target);
    }

    private static function exportString(string $value): string
    {
        return var_export($value, true);
    }

    /**
     * //phpcs:disable Generic.Files.LineLength.TooLong
     *
     * @param iterable<class-string, iterable<TransientTargetClass|TransientTargetMethod|TransientTargetParameter|TransientTargetProperty>> $targetByClass
     *
     * @return array<class-string, array<class-string|array{
     *     class-string,
     *     non-empty-string,
     *     2?:non-empty-string
     * }>>
     */
    private static function targetsToArray(iterable $targetByClass): array
    {
        $by = [];

        foreach ($targetByClass as $class => $targets) {
            foreach ($targets as $t) {
                if ($t instanceof TransientTargetClass) {
                    $by[$t->attribute][] = $class;

                    continue;
                }

                $a = [ $class ];

                if ($t instanceof TransientTargetParameter) {
                    $a[] = $t->method;
                }

                $a[] = $t->name;

                $by[$t->attribute][] = $a;
            }
        }

        return $by;
    }
}
